name: Sample CI/CD
on:
  push:
    branches:
      - "stage"

  pull_request:
    branches:
      - "stage"

jobs:
  build-coverage:
    name: install dependencies and test coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13

      - uses: actions/checkout@v3
        with:
          ref: stage

      - name: create config folder
        run: |
          mkdir -p config
          ls config
      - name: setup local.json for ci
        id: create-local-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "local.json"
          json: ${{ secrets.CONFIG_LOCAL_STAGE }}
          dir: "config/"

      # - name: install node dependencies
      #   run: |
      #     yarn install

      # - name: run test coverage
      #   run: |
      #     yarn run coverage

  deploy:
    name: build docker image and push to docker hub
    runs-on: ubuntu-latest
    needs: build-coverage

    steps:
      - uses: actions/checkout@v3
        with:
          ref: stage

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push api
        id: build-push-api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: demo/marketplace_api:stage